### ISSUE TITLE
Document type repeats in document ID

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ieee#5]
Example: https://demo.bibxml.org/ieee/IEEE_P1752_D-1.2020-04/

Document type is IEEE, document ID is IEEE P1752/D-1.2020-04. Seems redundant?

This is causing confusion exemplified by https://github.com/ietf-ribose/bibxml-service/issues/48.

**Comment by ronaldtse** [comment]
Unfortunately it is not redundant because IEEE offers other document identifiers that do not start with "IEEE". To the normal user it seems to be, but not in terms of correctness. 

My issue was more of the user experience.

**Comment by strogonoff** [comment]
> Unfortunately it is not redundant because IEEE offers other document identifiers that do not start with "IEEE".

But do they clash?

**Comment by strogonoff** [comment]
I think this is an issue of what is the standardized identifier shape for this document type. If we could have any supporting reference, I can see it being useful at eliminating such questions.

**Comment by ronaldtse** [comment]
That's why we are developing a PubID scheme for IEEE. There is no official reference today.

**Comment by strogonoff** [comment]
Maybe we could make that identifier not start with IEEE? Or is that a non-starter (sorry for the pun)?

**Comment by strogonoff** [comment]
The rest of the identifier is the actual document ID, so they surely aren‘t going to clash.

**Comment by ronaldtse** [comment]
> Maybe we could make that identifier not start with IEEE? Or is that a non-starter (sorry for the pun)?

But we need to distinguish the different IEEE docs. They have publications from the "former IEEE" called "IRE" and also "ANSI" standards that use those prefixes instead of "IEEE".

**Comment by strogonoff** [comment]
Shouldn’t we just use `type` for that? That way if IEEE gets renamed again we can just start using the new name for future citations; otherwise we have to upgrade all document type on all preexisting IEEE citations.

**Comment by ronaldtse** [comment]
Yes we should use type for that. Technically each document ID should belong to some schema/type.

**Comment by strogonoff** [comment]
That’d be nice, so then we’d have `{ type: IEEE, id: P1752/D-1.2020-04 }` instead of `{ type: IEEE, id: IEEE P1752/D-1.2020-04 }`.

I think it’d be better to make this transition earlier rather than later, to avoid breaking any links or API consumers.

As an aside, this applies to NIST as well, and possibly some other doctypes.

**Comment by ronaldtse** [comment]
> That’d be nice, so then we’d have `{ type: IEEE, id: P1752/D-1.2020-04 }` instead of `{ type: IEEE, id: IEEE P1752/D-1.2020-04 }`.

@andrew2net could we do this? Let me know what you think.

**Comment by andrew2net** [comment]
> > That’d be nice, so then we’d have `{ type: IEEE, id: P1752/D-1.2020-04 }` instead of `{ type: IEEE, id: IEEE P1752/D-1.2020-04 }`.
> 
> @andrew2net could we do this? Let me know what you think.

@ronaldtse I discussed this question with Nick a few months ago. He confirmed the id should be with type
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/5623890/148546136-568bfc6e-58fa-44ad-8c18-2c0b2caded8e.png">

**Comment by ronaldtse** [comment]
I think this warrants further discussion. And this discussion is a Relaton one. I can see that both approaches can be correct.

Approach 1:
* docidentifier represents the "schema" and the "label". In the case of "ISO 1234:2020", schema is "iso" or "ISO", the label is "ISO 1234:2020". (for those uninitiated, we can have "ISO/TR 1234:2020", "ISO/TR/WD 1234:2020", etc.

Approach 2:
* docidentifier represents the "schema" and "components of the label". i.e. there is never a full label. In the case of "ISO 1234:2020", schema is "iso" or "ISO", "number" is "1234", "edition" is "2020", type is "international standard".

So this is actually a comparison on whether we have a full string representation or a structured identifier.

Clearly:
* For users who cannot understand the ISO DocID schema, they **must** rely on a fully formatted string.
* For users who understand the ISO DocID schema, they can use the components to generate the string, or just to locate information about it.

Then the answer is, we should have both.

**Comment by strogonoff** [comment]
I see. The first “schema” interpretation makes sense to me. There are precedents without such redundancy, e.g. ISBNs and DOIs don’t have the extra prefix, but if such is the schema for other types then so be it.

**Comment by strogonoff** [comment]
It looks like we are giving different document identifiers different semantics, and this mixing will come and bite us later. I’ve been told that the first identifier is something called “PubID”, and only it (its `id` without the `type`) can be used by `formattedref` on relations. [It seems that `type` is used as a schema/namespace in some identifiers, and as publisher in others.](https://github.com/ietf-ribose/bibxml-service/issues/60#issuecomment-1008154738)

**Comment by ronaldtse** [comment]
> Also, I’ve been told that the first identifier is something called “PubID”

"PubID" is not a name (yet) and not a defined scheme that works across all publishers... Formally, the first identifier is the authoritative identifier (authoritative i.e. the publisher's identifier).

"formattedref" is a "string representation of the authoritative identifier". There is technically no "type" because this is a "string", but I'm sure @andrew2net can provide the "schema name" of the authoritative identifier.

> It looks like we are giving different document identifiers different semantics.

Yes. Different document identifiers **have** different semantics.

> It seems that type is used as a schema/namespace in some identifiers, and as publisher in others.

This *seems* to be the case but is not. Most publishers only have one identifier scheme, therefore the latter. Some publishers have *multiple identifier schemes*, e.g. IEEE. In this case we must differentiate the identifier schemes amongst the same publisher (e.g. `ieee` vs `ieee:aiee` vs `ieee:iso`).

Ping @andrew2net

**Comment by strogonoff** [comment]
> Yes. Different document identifiers have different semantics.
My point was that the the docid field should have consistent shared semantics for its contents. Individual identifiers can have meaningful differences, but they must share some core thing in common, otherwise they should not reside under the same property. So what’s that core thing is the question.

**Comment by strogonoff** [comment]
Right now I am fine with the primary attribute at least helping distinguish between the two kinds of identifiers, even if we mix concerns under docid. 

I will hide docid.type for primary identifiers in the UI, and show them as citeable.

We can probably close this issue.

**Comment by strogonoff** [comment]
@ronaldtse no, it was about different uses for different elements. Right now, marked as primary identifiers are citeable (maybe we should have called them that), and others are not, so that works for me.

**Comment by strogonoff** [comment]
Until now, we had a mix with no way for me to tel which  is which except by maintaining a hard-coded list of types.

**Comment by ronaldtse** [comment]
I see what you mean by "citable" now -- an identifier that people can cite a document with. Maybe we should adopt this notion for the "primary identifier"!

**Comment by ronaldtse** [comment]
@strogonoff I probably already dropped off, but this is good and we should document this...

**Comment by strogonoff** [comment]
I am bundling a mini-spec to IETF BibXML service docs, but want to create one separately as well. But ideally that one should be generated from LutaML.

**Comment by ronaldtse** [comment]
Agree with Nick's comment in rendering (but it is helpful for people to "locate/fetch a citation using DOI/ISBN"). Maybe another attribute could be used but there is an advantage of keeping all the "identifiers" under the same array.

Re: mini-spec, agree.

**Comment by strogonoff** [comment]
I will keep all identifiers searchable, but show only primary as citeable. Maybe that’s their shared value.
