### ISSUE TITLE
Wrong ID? 8802 vs. 802

### ISSUE THREAD

**Issue by strogonoff** [ietf-ribose/relaton-data-ieee#7]
See:

https://github.com/ietf-ribose/relaton-data-ieee/blob/c00657e051c9dbf55f5ff9c7c2c01063ec086c3d/data/ISO_IEC_IEEE_8802-11_AMD1.2012.yaml#L2-L21

**Comment by ronaldtse** [comment]
Actually this is intended, not an error.

https://www.iso.org/standard/62000.html
<img width="946" alt="image" src="https://user-images.githubusercontent.com/11865/152537022-f470a4a5-7ca7-46cf-abb2-1433d415a9c6.png">

This is an ISO/IEC/IEEE co-published document, and using the ISO/IEC style PubID. I believe the committee is aiming to map the IEEE 802.X series to ISO/IEC/IEEE 8802-X.

**Comment by strogonoff** [comment]
Got it, my bad.
